# coding: utf-8

"""
    Altana Atlas API

    Altana Atlas for Regulatory Risk and Trade Compliance  # noqa: E501

    OpenAPI spec version: {{ version or \"v0.0.1\" }}
    Contact: engineering@altanatech.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.product_api import ProductApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProductApi(unittest.TestCase):
    """ProductApi unit test stubs"""

    def setUp(self):
        self.api = ProductApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_product_by_id(self):
        """Test case for get_product_by_id

        Product ID  # noqa: E501
        """
        pass

    def test_get_product_companies(self):
        """Test case for get_product_companies

        Product Companies  # noqa: E501
        """
        pass

    def test_get_product_facilities(self):
        """Test case for get_product_facilities

        Product Facilities  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
