# coding: utf-8

"""
    Altana Atlas API

    Altana Atlas for Regulatory Risk and Trade Compliance  # noqa: E501

    OpenAPI spec version: {{ version or \"v0.0.1\" }}
    Contact: engineering@altanatech.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.base_risk import BaseRisk  # noqa: E501
from swagger_client.rest import ApiException


class TestBaseRisk(unittest.TestCase):
    """BaseRisk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaseRisk(self):
        """Test BaseRisk"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.base_risk.BaseRisk()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
