# coding: utf-8

"""
    Altana Atlas API

    Altana Atlas for Regulatory Risk and Trade Compliance  # noqa: E501

    OpenAPI spec version: v2.0.0-8
    Contact: engineering@altanatech.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.b_box_geo_json import BBoxGeoJson  # noqa: E501
from swagger_client.rest import ApiException


class TestBBoxGeoJson(unittest.TestCase):
    """BBoxGeoJson unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBBoxGeoJson(self):
        """Test BBoxGeoJson"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.b_box_geo_json.BBoxGeoJson()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
