# coding: utf-8

"""
    Altana Atlas API

    Altana Atlas for Regulatory Risk and Trade Compliance  # noqa: E501

    OpenAPI spec version: {{ version or \"v0.0.1\" }}
    Contact: engineering@altanatech.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.model_meta_data import ModelMetaData  # noqa: E501
from swagger_client.rest import ApiException


class TestModelMetaData(unittest.TestCase):
    """ModelMetaData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelMetaData(self):
        """Test ModelMetaData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.model_meta_data.ModelMetaData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
