# coding: utf-8

"""
    Altana Atlas API

    Altana Atlas for Regulatory Risk and Trade Compliance  # noqa: E501

    OpenAPI spec version: {{ version or \"v0.0.1\" }}
    Contact: engineering@altanatech.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.facility_api import FacilityApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFacilityApi(unittest.TestCase):
    """FacilityApi unit test stubs"""

    def setUp(self):
        self.api = FacilityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_facility_by_id(self):
        """Test case for get_facility_by_id

        Facility ID  # noqa: E501
        """
        pass

    def test_get_facility_products(self):
        """Test case for get_facility_products

        Facility Products  # noqa: E501
        """
        pass

    def test_get_facility_trading_partners(self):
        """Test case for get_facility_trading_partners

        Facility Trading Partners  # noqa: E501
        """
        pass

    def test_match_facility(self):
        """Test case for match_facility

        Facility Match  # noqa: E501
        """
        pass

    def test_search_facility(self):
        """Test case for search_facility

        Facility Search  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
