# coding: utf-8

"""
    Altana Atlas API

    Altana Atlas for Regulatory Risk and Trade Compliance  # noqa: E501

    OpenAPI spec version: v2.0.0-8
    Contact: engineering@altanatech.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.centroid_geo_json import CentroidGeoJson  # noqa: E501
from swagger_client.rest import ApiException


class TestCentroidGeoJson(unittest.TestCase):
    """CentroidGeoJson unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCentroidGeoJson(self):
        """Test CentroidGeoJson"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.centroid_geo_json.CentroidGeoJson()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
