# coding: utf-8

"""
    Altana Atlas API

    Altana Atlas for Regulatory Risk and Trade Compliance  # noqa: E501

    OpenAPI spec version: {{ version or \"v0.0.1\" }}
    Contact: engineering@altanatech.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.transaction_api import TransactionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTransactionApi(unittest.TestCase):
    """TransactionApi unit test stubs"""

    def setUp(self):
        self.api = TransactionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_transaction_risk(self):
        """Test case for transaction_risk

        Transaction Risk  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
