# coding: utf-8

"""
    Altana Atlas API

    Altana Atlas for Regulatory Risk and Trade Compliance  # noqa: E501

    OpenAPI spec version: v2.0.0-8
    Contact: engineering@altanatech.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_node import OneOfNode  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfNode(unittest.TestCase):
    """OneOfNode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfNode(self):
        """Test OneOfNode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_node.OneOfNode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
