# coding: utf-8

"""
    Altana Atlas API

    Altana Atlas for Regulatory Risk and Trade Compliance  # noqa: E501

    OpenAPI spec version: v2.0.0-8
    Contact: engineering@altanatech.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.denied_party_related_to_edge import DeniedPartyRelatedToEdge  # noqa: E501
from swagger_client.rest import ApiException


class TestDeniedPartyRelatedToEdge(unittest.TestCase):
    """DeniedPartyRelatedToEdge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeniedPartyRelatedToEdge(self):
        """Test DeniedPartyRelatedToEdge"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.denied_party_related_to_edge.DeniedPartyRelatedToEdge()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
