# coding: utf-8

"""
    Altana Atlas API

    Altana Atlas for Regulatory Risk and Trade Compliance  # noqa: E501

    OpenAPI spec version: v2.0.0-8
    Contact: engineering@altanatech.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.field_descriptions import FieldDescriptions  # noqa: E501
from swagger_client.rest import ApiException


class TestFieldDescriptions(unittest.TestCase):
    """FieldDescriptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldDescriptions(self):
        """Test FieldDescriptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.field_descriptions.FieldDescriptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
