# coding: utf-8

# flake8: noqa
"""
    Altana Atlas API

    Altana Atlas for Regulatory Risk and Trade Compliance  # noqa: E501

    OpenAPI spec version: {{ version or \"v0.0.1\" }}
    Contact: engineering@altanatech.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.base_edge import BaseEdge
from swagger_client.models.base_risk import BaseRisk
from swagger_client.models.companies import Companies
from swagger_client.models.company import Company
from swagger_client.models.company_context import CompanyContext
from swagger_client.models.coordinates import Coordinates
from swagger_client.models.declared_goods import DeclaredGoods
from swagger_client.models.edge import Edge
from swagger_client.models.edges import Edges
from swagger_client.models.facilities import Facilities
from swagger_client.models.facility import Facility
from swagger_client.models.facility_trading_partners import FacilityTradingPartners
from swagger_client.models.geo_coder_meta_data import GeoCoderMetaData
from swagger_client.models.goods_measure import GoodsMeasure
from swagger_client.models.hs_misclassification_risk import HSMisclassificationRisk
from swagger_client.models.inter_facility_edge import InterFacilityEdge
from swagger_client.models.model_meta_data import ModelMetaData
from swagger_client.models.one_of_edge import OneOfEdge
from swagger_client.models.one_of_risk import OneOfRisk
from swagger_client.models.party import Party
from swagger_client.models.predicted_goods import PredictedGoods
from swagger_client.models.product import Product
from swagger_client.models.products import Products
from swagger_client.models.restriction import Restriction
from swagger_client.models.risk import Risk
from swagger_client.models.tariff import Tariff
from swagger_client.models.trade_relationship import TradeRelationship
from swagger_client.models.trade_route import TradeRoute
from swagger_client.models.trading_partner_edge import TradingPartnerEdge
from swagger_client.models.trading_partners import TradingPartners
from swagger_client.models.trading_partners_edge import TradingPartnersEdge
from swagger_client.models.transaction_record import TransactionRecord
from swagger_client.models.transaction_risk import TransactionRisk
