# coding: utf-8

"""
    Altana Atlas API

    Altana Atlas for Regulatory Risk and Trade Compliance  # noqa: E501

    OpenAPI spec version: v2.0.0-8
    Contact: engineering@altanatech.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BaseEdge(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'additional_fields': 'object',
        'edge_type': 'str'
    }

    attribute_map = {
        'additional_fields': 'additional_fields',
        'edge_type': 'edge_type'
    }

    def __init__(self, additional_fields=None, edge_type=None):  # noqa: E501
        """BaseEdge - a model defined in Swagger"""  # noqa: E501
        self._additional_fields = None
        self._edge_type = None
        self.discriminator = None
        if additional_fields is not None:
            self.additional_fields = additional_fields
        if edge_type is not None:
            self.edge_type = edge_type

    @property
    def additional_fields(self):
        """Gets the additional_fields of this BaseEdge.  # noqa: E501

        Additional fields that are only populated when getting a resource by its ID  # noqa: E501

        :return: The additional_fields of this BaseEdge.  # noqa: E501
        :rtype: object
        """
        return self._additional_fields

    @additional_fields.setter
    def additional_fields(self, additional_fields):
        """Sets the additional_fields of this BaseEdge.

        Additional fields that are only populated when getting a resource by its ID  # noqa: E501

        :param additional_fields: The additional_fields of this BaseEdge.  # noqa: E501
        :type: object
        """

        self._additional_fields = additional_fields

    @property
    def edge_type(self):
        """Gets the edge_type of this BaseEdge.  # noqa: E501

        The type of this edge  # noqa: E501

        :return: The edge_type of this BaseEdge.  # noqa: E501
        :rtype: str
        """
        return self._edge_type

    @edge_type.setter
    def edge_type(self, edge_type):
        """Sets the edge_type of this BaseEdge.

        The type of this edge  # noqa: E501

        :param edge_type: The edge_type of this BaseEdge.  # noqa: E501
        :type: str
        """

        self._edge_type = edge_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BaseEdge, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BaseEdge):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
