# coding: utf-8

"""
    Altana Atlas API

    Altana Atlas for Regulatory Risk and Trade Compliance  # noqa: E501

    OpenAPI spec version: {{ version or \"v0.0.1\" }}
    Contact: engineering@altanatech.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BaseEdge(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'edge_type': 'str',
        'edge_canon_id': 'str'
    }

    attribute_map = {
        'edge_type': 'edge_type',
        'edge_canon_id': 'edge_canon_id'
    }

    def __init__(self, edge_type=None, edge_canon_id=None):  # noqa: E501
        """BaseEdge - a model defined in Swagger"""  # noqa: E501
        self._edge_type = None
        self._edge_canon_id = None
        self.discriminator = None
        if edge_type is not None:
            self.edge_type = edge_type
        if edge_canon_id is not None:
            self.edge_canon_id = edge_canon_id

    @property
    def edge_type(self):
        """Gets the edge_type of this BaseEdge.  # noqa: E501


        :return: The edge_type of this BaseEdge.  # noqa: E501
        :rtype: str
        """
        return self._edge_type

    @edge_type.setter
    def edge_type(self, edge_type):
        """Sets the edge_type of this BaseEdge.


        :param edge_type: The edge_type of this BaseEdge.  # noqa: E501
        :type: str
        """

        self._edge_type = edge_type

    @property
    def edge_canon_id(self):
        """Gets the edge_canon_id of this BaseEdge.  # noqa: E501


        :return: The edge_canon_id of this BaseEdge.  # noqa: E501
        :rtype: str
        """
        return self._edge_canon_id

    @edge_canon_id.setter
    def edge_canon_id(self, edge_canon_id):
        """Sets the edge_canon_id of this BaseEdge.


        :param edge_canon_id: The edge_canon_id of this BaseEdge.  # noqa: E501
        :type: str
        """

        self._edge_canon_id = edge_canon_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BaseEdge, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BaseEdge):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
