# coding: utf-8

"""
    Altana Atlas API

    Altana Atlas for Regulatory Risk and Trade Compliance  # noqa: E501

    OpenAPI spec version: v2.0.0-8
    Contact: engineering@altanatech.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HSCodeCount(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'count': 'int',
        'hs_code': 'str'
    }

    attribute_map = {
        'count': 'count',
        'hs_code': 'hs_code'
    }

    def __init__(self, count=None, hs_code=None):  # noqa: E501
        """HSCodeCount - a model defined in Swagger"""  # noqa: E501
        self._count = None
        self._hs_code = None
        self.discriminator = None
        if count is not None:
            self.count = count
        if hs_code is not None:
            self.hs_code = hs_code

    @property
    def count(self):
        """Gets the count of this HSCodeCount.  # noqa: E501


        :return: The count of this HSCodeCount.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this HSCodeCount.


        :param count: The count of this HSCodeCount.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def hs_code(self):
        """Gets the hs_code of this HSCodeCount.  # noqa: E501


        :return: The hs_code of this HSCodeCount.  # noqa: E501
        :rtype: str
        """
        return self._hs_code

    @hs_code.setter
    def hs_code(self, hs_code):
        """Sets the hs_code of this HSCodeCount.


        :param hs_code: The hs_code of this HSCodeCount.  # noqa: E501
        :type: str
        """

        self._hs_code = hs_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HSCodeCount, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HSCodeCount):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
