# coding: utf-8

"""
    Altana Atlas API

    Altana Atlas for Regulatory Risk and Trade Compliance  # noqa: E501

    OpenAPI spec version: v2.0.0-8
    Contact: engineering@altanatech.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.base_edge import BaseEdge  # noqa: F401,E501

class OperatedByEdge(BaseEdge):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bvd_id': 'list[str]',
        'confidence': 'float',
        'destination_id': 'str',
        'operated_by_id': 'str',
        'source_id': 'str',
        'sources': 'list[str]'
    }
    if hasattr(BaseEdge, "swagger_types"):
        swagger_types.update(BaseEdge.swagger_types)

    attribute_map = {
        'bvd_id': 'bvd_id',
        'confidence': 'confidence',
        'destination_id': 'destination_id',
        'operated_by_id': 'operated_by_id',
        'source_id': 'source_id',
        'sources': 'sources'
    }
    if hasattr(BaseEdge, "attribute_map"):
        attribute_map.update(BaseEdge.attribute_map)

    def __init__(self, bvd_id=None, confidence=None, destination_id=None, operated_by_id=None, source_id=None, sources=None, *args, **kwargs):  # noqa: E501
        """OperatedByEdge - a model defined in Swagger"""  # noqa: E501
        self._bvd_id = None
        self._confidence = None
        self._destination_id = None
        self._operated_by_id = None
        self._source_id = None
        self._sources = None
        self.discriminator = None
        if bvd_id is not None:
            self.bvd_id = bvd_id
        if confidence is not None:
            self.confidence = confidence
        if destination_id is not None:
            self.destination_id = destination_id
        if operated_by_id is not None:
            self.operated_by_id = operated_by_id
        if source_id is not None:
            self.source_id = source_id
        if sources is not None:
            self.sources = sources
        BaseEdge.__init__(self, *args, **kwargs)

    @property
    def bvd_id(self):
        """Gets the bvd_id of this OperatedByEdge.  # noqa: E501

        The ID associating the Altana operated by edge to the BVD operated by edge  # noqa: E501

        :return: The bvd_id of this OperatedByEdge.  # noqa: E501
        :rtype: list[str]
        """
        return self._bvd_id

    @bvd_id.setter
    def bvd_id(self, bvd_id):
        """Sets the bvd_id of this OperatedByEdge.

        The ID associating the Altana operated by edge to the BVD operated by edge  # noqa: E501

        :param bvd_id: The bvd_id of this OperatedByEdge.  # noqa: E501
        :type: list[str]
        """

        self._bvd_id = bvd_id

    @property
    def confidence(self):
        """Gets the confidence of this OperatedByEdge.  # noqa: E501

        The confidence of the clustering that a facility is operated by a company  # noqa: E501

        :return: The confidence of this OperatedByEdge.  # noqa: E501
        :rtype: float
        """
        return self._confidence

    @confidence.setter
    def confidence(self, confidence):
        """Sets the confidence of this OperatedByEdge.

        The confidence of the clustering that a facility is operated by a company  # noqa: E501

        :param confidence: The confidence of this OperatedByEdge.  # noqa: E501
        :type: float
        """

        self._confidence = confidence

    @property
    def destination_id(self):
        """Gets the destination_id of this OperatedByEdge.  # noqa: E501

        The company_canon_id of the company that operates the facility  # noqa: E501

        :return: The destination_id of this OperatedByEdge.  # noqa: E501
        :rtype: str
        """
        return self._destination_id

    @destination_id.setter
    def destination_id(self, destination_id):
        """Sets the destination_id of this OperatedByEdge.

        The company_canon_id of the company that operates the facility  # noqa: E501

        :param destination_id: The destination_id of this OperatedByEdge.  # noqa: E501
        :type: str
        """

        self._destination_id = destination_id

    @property
    def operated_by_id(self):
        """Gets the operated_by_id of this OperatedByEdge.  # noqa: E501

        A unique identifier for an operated by edge  # noqa: E501

        :return: The operated_by_id of this OperatedByEdge.  # noqa: E501
        :rtype: str
        """
        return self._operated_by_id

    @operated_by_id.setter
    def operated_by_id(self, operated_by_id):
        """Sets the operated_by_id of this OperatedByEdge.

        A unique identifier for an operated by edge  # noqa: E501

        :param operated_by_id: The operated_by_id of this OperatedByEdge.  # noqa: E501
        :type: str
        """

        self._operated_by_id = operated_by_id

    @property
    def source_id(self):
        """Gets the source_id of this OperatedByEdge.  # noqa: E501

        The facility_canon_id of the facility that is operated by the company  # noqa: E501

        :return: The source_id of this OperatedByEdge.  # noqa: E501
        :rtype: str
        """
        return self._source_id

    @source_id.setter
    def source_id(self, source_id):
        """Sets the source_id of this OperatedByEdge.

        The facility_canon_id of the facility that is operated by the company  # noqa: E501

        :param source_id: The source_id of this OperatedByEdge.  # noqa: E501
        :type: str
        """

        self._source_id = source_id

    @property
    def sources(self):
        """Gets the sources of this OperatedByEdge.  # noqa: E501

        A list of data sources for the information  # noqa: E501

        :return: The sources of this OperatedByEdge.  # noqa: E501
        :rtype: list[str]
        """
        return self._sources

    @sources.setter
    def sources(self, sources):
        """Sets the sources of this OperatedByEdge.

        A list of data sources for the information  # noqa: E501

        :param sources: The sources of this OperatedByEdge.  # noqa: E501
        :type: list[str]
        """

        self._sources = sources

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OperatedByEdge, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OperatedByEdge):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
