# coding: utf-8

"""
    Altana Atlas API

    Altana Atlas for Regulatory Risk and Trade Compliance  # noqa: E501

    OpenAPI spec version: v2.0.0-8
    Contact: engineering@altanatech.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.base_edge import BaseEdge  # noqa: F401,E501

class OwnedByEdge(BaseEdge):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'destination_id': 'str',
        'direct_pct': 'float',
        'owned_by_id': 'str',
        'ownership_type': 'str',
        'source_id': 'str',
        'sources': 'list[str]',
        'total_pct': 'float'
    }
    if hasattr(BaseEdge, "swagger_types"):
        swagger_types.update(BaseEdge.swagger_types)

    attribute_map = {
        'destination_id': 'destination_id',
        'direct_pct': 'direct_pct',
        'owned_by_id': 'owned_by_id',
        'ownership_type': 'ownership_type',
        'source_id': 'source_id',
        'sources': 'sources',
        'total_pct': 'total_pct'
    }
    if hasattr(BaseEdge, "attribute_map"):
        attribute_map.update(BaseEdge.attribute_map)

    def __init__(self, destination_id=None, direct_pct=None, owned_by_id=None, ownership_type=None, source_id=None, sources=None, total_pct=None, *args, **kwargs):  # noqa: E501
        """OwnedByEdge - a model defined in Swagger"""  # noqa: E501
        self._destination_id = None
        self._direct_pct = None
        self._owned_by_id = None
        self._ownership_type = None
        self._source_id = None
        self._sources = None
        self._total_pct = None
        self.discriminator = None
        if destination_id is not None:
            self.destination_id = destination_id
        if direct_pct is not None:
            self.direct_pct = direct_pct
        if owned_by_id is not None:
            self.owned_by_id = owned_by_id
        if ownership_type is not None:
            self.ownership_type = ownership_type
        if source_id is not None:
            self.source_id = source_id
        if sources is not None:
            self.sources = sources
        if total_pct is not None:
            self.total_pct = total_pct
        BaseEdge.__init__(self, *args, **kwargs)

    @property
    def destination_id(self):
        """Gets the destination_id of this OwnedByEdge.  # noqa: E501

        The company_canon_id of the owner company that owns the source company  # noqa: E501

        :return: The destination_id of this OwnedByEdge.  # noqa: E501
        :rtype: str
        """
        return self._destination_id

    @destination_id.setter
    def destination_id(self, destination_id):
        """Sets the destination_id of this OwnedByEdge.

        The company_canon_id of the owner company that owns the source company  # noqa: E501

        :param destination_id: The destination_id of this OwnedByEdge.  # noqa: E501
        :type: str
        """

        self._destination_id = destination_id

    @property
    def direct_pct(self):
        """Gets the direct_pct of this OwnedByEdge.  # noqa: E501

        The company's direct stake percentage  # noqa: E501

        :return: The direct_pct of this OwnedByEdge.  # noqa: E501
        :rtype: float
        """
        return self._direct_pct

    @direct_pct.setter
    def direct_pct(self, direct_pct):
        """Sets the direct_pct of this OwnedByEdge.

        The company's direct stake percentage  # noqa: E501

        :param direct_pct: The direct_pct of this OwnedByEdge.  # noqa: E501
        :type: float
        """

        self._direct_pct = direct_pct

    @property
    def owned_by_id(self):
        """Gets the owned_by_id of this OwnedByEdge.  # noqa: E501

        A unique identifier for an owned by edge  # noqa: E501

        :return: The owned_by_id of this OwnedByEdge.  # noqa: E501
        :rtype: str
        """
        return self._owned_by_id

    @owned_by_id.setter
    def owned_by_id(self, owned_by_id):
        """Sets the owned_by_id of this OwnedByEdge.

        A unique identifier for an owned by edge  # noqa: E501

        :param owned_by_id: The owned_by_id of this OwnedByEdge.  # noqa: E501
        :type: str
        """

        self._owned_by_id = owned_by_id

    @property
    def ownership_type(self):
        """Gets the ownership_type of this OwnedByEdge.  # noqa: E501

        The shareholder ownership type (e.g. GUO_25c_JO, GUO_25c, GUO_50c)  # noqa: E501

        :return: The ownership_type of this OwnedByEdge.  # noqa: E501
        :rtype: str
        """
        return self._ownership_type

    @ownership_type.setter
    def ownership_type(self, ownership_type):
        """Sets the ownership_type of this OwnedByEdge.

        The shareholder ownership type (e.g. GUO_25c_JO, GUO_25c, GUO_50c)  # noqa: E501

        :param ownership_type: The ownership_type of this OwnedByEdge.  # noqa: E501
        :type: str
        """

        self._ownership_type = ownership_type

    @property
    def source_id(self):
        """Gets the source_id of this OwnedByEdge.  # noqa: E501

        The company_canon_id of the compnay that is owned by the destination company  # noqa: E501

        :return: The source_id of this OwnedByEdge.  # noqa: E501
        :rtype: str
        """
        return self._source_id

    @source_id.setter
    def source_id(self, source_id):
        """Sets the source_id of this OwnedByEdge.

        The company_canon_id of the compnay that is owned by the destination company  # noqa: E501

        :param source_id: The source_id of this OwnedByEdge.  # noqa: E501
        :type: str
        """

        self._source_id = source_id

    @property
    def sources(self):
        """Gets the sources of this OwnedByEdge.  # noqa: E501

        A list of data sources for the information  # noqa: E501

        :return: The sources of this OwnedByEdge.  # noqa: E501
        :rtype: list[str]
        """
        return self._sources

    @sources.setter
    def sources(self, sources):
        """Sets the sources of this OwnedByEdge.

        A list of data sources for the information  # noqa: E501

        :param sources: The sources of this OwnedByEdge.  # noqa: E501
        :type: list[str]
        """

        self._sources = sources

    @property
    def total_pct(self):
        """Gets the total_pct of this OwnedByEdge.  # noqa: E501

        The company's total stake percentage  # noqa: E501

        :return: The total_pct of this OwnedByEdge.  # noqa: E501
        :rtype: float
        """
        return self._total_pct

    @total_pct.setter
    def total_pct(self, total_pct):
        """Sets the total_pct of this OwnedByEdge.

        The company's total stake percentage  # noqa: E501

        :param total_pct: The total_pct of this OwnedByEdge.  # noqa: E501
        :type: float
        """

        self._total_pct = total_pct

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OwnedByEdge, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OwnedByEdge):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
