# coding: utf-8

"""
    Altana Atlas API

    Altana Atlas for Regulatory Risk and Trade Compliance  # noqa: E501

    OpenAPI spec version: {{ version or \"v0.0.1\" }}
    Contact: engineering@altanatech.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Party(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'country': 'str',
        'full_address': 'str',
        'id': 'str',
        'name': 'str'
    }

    attribute_map = {
        'country': 'country',
        'full_address': 'full_address',
        'id': 'id',
        'name': 'name'
    }

    def __init__(self, country=None, full_address=None, id=None, name=None):  # noqa: E501
        """Party - a model defined in Swagger"""  # noqa: E501
        self._country = None
        self._full_address = None
        self._id = None
        self._name = None
        self.discriminator = None
        if country is not None:
            self.country = country
        self.full_address = full_address
        if id is not None:
            self.id = id
        self.name = name

    @property
    def country(self):
        """Gets the country of this Party.  # noqa: E501

        ISO2 code  # noqa: E501

        :return: The country of this Party.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this Party.

        ISO2 code  # noqa: E501

        :param country: The country of this Party.  # noqa: E501
        :type: str
        """

        self._country = country

    @property
    def full_address(self):
        """Gets the full_address of this Party.  # noqa: E501

        Address data (not used for risk calculation)  # noqa: E501

        :return: The full_address of this Party.  # noqa: E501
        :rtype: str
        """
        return self._full_address

    @full_address.setter
    def full_address(self, full_address):
        """Sets the full_address of this Party.

        Address data (not used for risk calculation)  # noqa: E501

        :param full_address: The full_address of this Party.  # noqa: E501
        :type: str
        """
        if full_address is None:
            raise ValueError("Invalid value for `full_address`, must not be `None`")  # noqa: E501

        self._full_address = full_address

    @property
    def id(self):
        """Gets the id of this Party.  # noqa: E501

        UUID of party (not used for risk calculation)  # noqa: E501

        :return: The id of this Party.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Party.

        UUID of party (not used for risk calculation)  # noqa: E501

        :param id: The id of this Party.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Party.  # noqa: E501

        Text name of the party  # noqa: E501

        :return: The name of this Party.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Party.

        Text name of the party  # noqa: E501

        :param name: The name of this Party.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Party, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Party):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
