# coding: utf-8

"""
    Altana Atlas API

    Altana Atlas for Regulatory Risk and Trade Compliance  # noqa: E501

    OpenAPI spec version: {{ version or \"v0.0.1\" }}
    Contact: engineering@altanatech.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.base_edge import BaseEdge  # noqa: F401,E501

class TradingPartnersEdge(BaseEdge):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'company_canon_ids': 'list[str]',
        'trade_relationships': 'list[TradeRelationship]'
    }
    if hasattr(BaseEdge, "swagger_types"):
        swagger_types.update(BaseEdge.swagger_types)

    attribute_map = {
        'company_canon_ids': 'company_canon_ids',
        'trade_relationships': 'trade_relationships'
    }
    if hasattr(BaseEdge, "attribute_map"):
        attribute_map.update(BaseEdge.attribute_map)

    def __init__(self, company_canon_ids=None, trade_relationships=None, *args, **kwargs):  # noqa: E501
        """TradingPartnersEdge - a model defined in Swagger"""  # noqa: E501
        self._company_canon_ids = None
        self._trade_relationships = None
        self.discriminator = None
        if company_canon_ids is not None:
            self.company_canon_ids = company_canon_ids
        if trade_relationships is not None:
            self.trade_relationships = trade_relationships
        BaseEdge.__init__(self, *args, **kwargs)

    @property
    def company_canon_ids(self):
        """Gets the company_canon_ids of this TradingPartnersEdge.  # noqa: E501


        :return: The company_canon_ids of this TradingPartnersEdge.  # noqa: E501
        :rtype: list[str]
        """
        return self._company_canon_ids

    @company_canon_ids.setter
    def company_canon_ids(self, company_canon_ids):
        """Sets the company_canon_ids of this TradingPartnersEdge.


        :param company_canon_ids: The company_canon_ids of this TradingPartnersEdge.  # noqa: E501
        :type: list[str]
        """

        self._company_canon_ids = company_canon_ids

    @property
    def trade_relationships(self):
        """Gets the trade_relationships of this TradingPartnersEdge.  # noqa: E501


        :return: The trade_relationships of this TradingPartnersEdge.  # noqa: E501
        :rtype: list[TradeRelationship]
        """
        return self._trade_relationships

    @trade_relationships.setter
    def trade_relationships(self, trade_relationships):
        """Sets the trade_relationships of this TradingPartnersEdge.


        :param trade_relationships: The trade_relationships of this TradingPartnersEdge.  # noqa: E501
        :type: list[TradeRelationship]
        """

        self._trade_relationships = trade_relationships

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TradingPartnersEdge, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TradingPartnersEdge):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
