# coding: utf-8

"""
    Altana Atlas API

    Altana Atlas for Regulatory Risk and Trade Compliance  # noqa: E501

    OpenAPI spec version: {{ version or \"v0.0.1\" }}
    Contact: engineering@altanatech.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TradingPartners(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'num_results': 'int',
        'page_size': 'int',
        'page_num': 'int',
        'companies': 'list[Company]',
        'edges': 'list[Edge]'
    }

    attribute_map = {
        'num_results': 'num_results',
        'page_size': 'page_size',
        'page_num': 'page_num',
        'companies': 'companies',
        'edges': 'edges'
    }

    def __init__(self, num_results=None, page_size=None, page_num=None, companies=None, edges=None):  # noqa: E501
        """TradingPartners - a model defined in Swagger"""  # noqa: E501
        self._num_results = None
        self._page_size = None
        self._page_num = None
        self._companies = None
        self._edges = None
        self.discriminator = None
        if num_results is not None:
            self.num_results = num_results
        if page_size is not None:
            self.page_size = page_size
        if page_num is not None:
            self.page_num = page_num
        if companies is not None:
            self.companies = companies
        if edges is not None:
            self.edges = edges

    @property
    def num_results(self):
        """Gets the num_results of this TradingPartners.  # noqa: E501


        :return: The num_results of this TradingPartners.  # noqa: E501
        :rtype: int
        """
        return self._num_results

    @num_results.setter
    def num_results(self, num_results):
        """Sets the num_results of this TradingPartners.


        :param num_results: The num_results of this TradingPartners.  # noqa: E501
        :type: int
        """

        self._num_results = num_results

    @property
    def page_size(self):
        """Gets the page_size of this TradingPartners.  # noqa: E501


        :return: The page_size of this TradingPartners.  # noqa: E501
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size):
        """Sets the page_size of this TradingPartners.


        :param page_size: The page_size of this TradingPartners.  # noqa: E501
        :type: int
        """

        self._page_size = page_size

    @property
    def page_num(self):
        """Gets the page_num of this TradingPartners.  # noqa: E501


        :return: The page_num of this TradingPartners.  # noqa: E501
        :rtype: int
        """
        return self._page_num

    @page_num.setter
    def page_num(self, page_num):
        """Sets the page_num of this TradingPartners.


        :param page_num: The page_num of this TradingPartners.  # noqa: E501
        :type: int
        """

        self._page_num = page_num

    @property
    def companies(self):
        """Gets the companies of this TradingPartners.  # noqa: E501


        :return: The companies of this TradingPartners.  # noqa: E501
        :rtype: list[Company]
        """
        return self._companies

    @companies.setter
    def companies(self, companies):
        """Sets the companies of this TradingPartners.


        :param companies: The companies of this TradingPartners.  # noqa: E501
        :type: list[Company]
        """

        self._companies = companies

    @property
    def edges(self):
        """Gets the edges of this TradingPartners.  # noqa: E501


        :return: The edges of this TradingPartners.  # noqa: E501
        :rtype: list[Edge]
        """
        return self._edges

    @edges.setter
    def edges(self, edges):
        """Sets the edges of this TradingPartners.


        :param edges: The edges of this TradingPartners.  # noqa: E501
        :type: list[Edge]
        """

        self._edges = edges

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TradingPartners, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TradingPartners):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
