# coding: utf-8

"""
    Altana Atlas API

    Altana Atlas for Regulatory Risk and Trade Compliance  # noqa: E501

    OpenAPI spec version: v2.0.0-8
    Contact: engineering@altanatech.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TypesEdges(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'edge_name': 'TypesEdgesEdgeName'
    }

    attribute_map = {
        'edge_name': 'edge_name'
    }

    def __init__(self, edge_name=None):  # noqa: E501
        """TypesEdges - a model defined in Swagger"""  # noqa: E501
        self._edge_name = None
        self.discriminator = None
        if edge_name is not None:
            self.edge_name = edge_name

    @property
    def edge_name(self):
        """Gets the edge_name of this TypesEdges.  # noqa: E501


        :return: The edge_name of this TypesEdges.  # noqa: E501
        :rtype: TypesEdgesEdgeName
        """
        return self._edge_name

    @edge_name.setter
    def edge_name(self, edge_name):
        """Sets the edge_name of this TypesEdges.


        :param edge_name: The edge_name of this TypesEdges.  # noqa: E501
        :type: TypesEdgesEdgeName
        """

        self._edge_name = edge_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TypesEdges, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TypesEdges):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
